sudo: required
services:
  - docker

before_install: 
  - docker build -t bs/docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true bs/docker-react-dev npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-526458714846"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY